/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import dao.NhanvienDAO;
import dao.impl.NhanvienImpl;
import entity.NhanVien;

/**
 *
 * @author LENOVO
 */
public class QL extends javax.swing.JFrame {

	private NhanvienDAO nhanvienDAO = new NhanvienImpl();
	public static String taiKhoan = "taikhoannv3";

	private int chucvu;

	/**
	 * Creates new form QL
	 */

	public QL(String tk) {
		taiKhoan = tk;
		initComponents(tk);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents(String tk) {

		
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		lblThongTinNV = new javax.swing.JLabel();
		btnDangXuat = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		TracuuKH = new javax.swing.JMenuItem();
		QLKH = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		TCNV = new javax.swing.JMenuItem();
		QLNV = new javax.swing.JMenuItem();
		ChamCong = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenu5 = new javax.swing.JMenu();
		TKS = new javax.swing.JMenuItem();
		TCS = new javax.swing.JMenuItem();
		QLS = new javax.swing.JMenuItem();
		jMenu6 = new javax.swing.JMenu();
		TCHD = new javax.swing.JMenuItem();
		QLHD = new javax.swing.JMenuItem();
		TKHD = new javax.swing.JMenuItem();
		jMenu7 = new javax.swing.JMenu();
		TCNXB = new javax.swing.JMenuItem();
		QLNXB = new javax.swing.JMenuItem();
		jMenu8 = new javax.swing.JMenu();
		TCTG = new javax.swing.JMenuItem();
		QLTG = new javax.swing.JMenuItem();
		ThemTK = new javax.swing.JMenuItem();
		SuaTK = new javax.swing.JMenuItem();
		XoaTK = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(240,240,240));
		

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("Thông tin đăng nhập");

		btnDangXuat.setBackground(new java.awt.Color(255, 102, 0));
		btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		btnDangXuat.setText("Đăng Xuất");
		btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDangXuatActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblThongTinNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1140, Short.MAX_VALUE)
                .addComponent(btnDangXuat)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(606, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThongTinNV)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

		jMenuBar1.setToolTipText("");

		jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kh.png"))); // NOI18N
		jMenu1.setText("Khách Hàng");
		jMenu1.setMargin(new java.awt.Insets(0, 10, 0, 10));

		TracuuKH.setText("Tra cứu khách hàng");
		TracuuKH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TracuuKHActionPerformed(evt);
			}
		});
		jMenu1.add(TracuuKH);

		QLKH.setText("Quản lý khách hàng");
		QLKH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QLKHActionPerformed(evt);
			}
		});
		jMenu1.add(QLKH);

		jMenuBar1.add(jMenu1);

		jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/about.png"))); // NOI18N
		jMenu3.setText("Nhân Viên");
		jMenu3.setMargin(new java.awt.Insets(0, 10, 0, 10));

		TCNV.setText("Tra cứu nhân viên");
		TCNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TCNVActionPerformed(evt);
			}
		});
		jMenu3.add(TCNV);

		QLNV.setText("Quản lý nhân viên");
		QLNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QLNVActionPerformed(evt);
			}
		});
		jMenu3.add(QLNV);

		ChamCong.setText("Chấm công");
		ChamCong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ChamCongActionPerformed(evt);
			}
		});
		jMenu3.add(ChamCong);

		jMenuBar1.add(jMenu3);

		jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sach.jpg"))); // NOI18N
		jMenu5.setText("Sách");
		jMenu5.setMargin(new java.awt.Insets(0, 10, 0, 10));

		TKS.setText("Thống kê");
		TKS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TKSActionPerformed(evt);
			}
		});
		jMenu5.add(TKS);

		TCS.setText("Tra cứu sách");
		TCS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TCSActionPerformed(evt);
			}
		});
		jMenu5.add(TCS);

		QLS.setText("Quản lý sách");
		QLS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QLSActionPerformed(evt);
			}
		});
		jMenu5.add(QLS);

		jMenuBar1.add(jMenu5);

		jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Order.png"))); // NOI18N
		jMenu6.setText("Hóa Đơn");
		jMenu6.setMargin(new java.awt.Insets(0, 10, 0, 10));

		TCHD.setText("Tra cứu");
		TCHD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TCHDActionPerformed(evt);
			}
		});
		jMenu6.add(TCHD);

		QLHD.setText("Lập hóa đơn");
		QLHD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QLHDActionPerformed(evt);
			}
		});
		jMenu6.add(QLHD);

		TKHD.setText("Thống kê");
		TKHD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TKHDActionPerformed(evt);
			}
		});
		jMenu6.add(TKHD);

		jMenuBar1.add(jMenu6);

		jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NXB.png"))); // NOI18N
		jMenu7.setText("Nhà Xuất Bản");
		jMenu7.setMargin(new java.awt.Insets(0, 10, 0, 10));

		TCNXB.setText("Tra cứu NXB");
		TCNXB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TCNXBActionPerformed(evt);
			}
		});
		jMenu7.add(TCNXB);

		QLNXB.setText("Quản lý NXB");
		QLNXB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QLNXBActionPerformed(evt);
			}
		});
		jMenu7.add(QLNXB);

		jMenuBar1.add(jMenu7);

		jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tacGia.png"))); // NOI18N
		jMenu8.setText("Tác Giả");
		jMenu8.setMargin(new java.awt.Insets(0, 10, 0, 10));

		TCTG.setText("Tra cứu tác giả");
		TCTG.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TCTGActionPerformed(evt);
			}
		});
		jMenu8.add(TCTG);

		QLTG.setText("Quản lý tác giả");
		QLTG.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QLTGActionPerformed(evt);
			}
		});
		jMenu8.add(QLTG);

		jMenuBar1.add(jMenu8);

		setJMenuBar(jMenuBar1);

		jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TK.jpg"))); // NOI18N
		jMenu2.setText("Tài Khoản");
		jMenu2.setMargin(new java.awt.Insets(0, 10, 0, 10));

		ThemTK.setText("Thêm Tài khoản");
		ThemTK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ThemTKActionPerformed(evt);
			}
		});
		jMenu2.add(ThemTK);

		SuaTK.setText("Cập Nhật Tài Khoản");
		SuaTK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SuaTKActionPerformed(evt);
			}
		});
		jMenu2.add(SuaTK);

		XoaTK.setText("Xóa Tài Khoản");
		XoaTK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				XoaTKActionPerformed(evt);
			}
		});
		jMenu2.add(XoaTK);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);

		// =========================================================
		setThôngTinNV(tk);

	}// </editor-fold>

	private void setThôngTinNV(String tk) {
		NhanVien nv = nhanvienDAO.getNhanVien_TaiKhoan(tk);

		String ttNV = "";

		if (nv.getMaNV().equals("NV00001")) {
			ttNV = "Admin: " + nv.getTenNV();
			chucvu = -1;
		} else if (nv.getQuanLyNV().getMaNV().equals("NV00001")) {
			chucvu = 0;
			ttNV = "Quản lý: " + nv.getTenNV();
		} else if (!nv.getQuanLyNV().getMaNV().equals("NV00001")) {
			ttNV = "Nhân viên: " + nv.getTenNV();
			chucvu = 1;
		}

		lblThongTinNV.setText(ttNV);

	}

	private void TKSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TKSActionPerformed
		// TODO add your handling code here:
		new Thongkesach().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_TKSActionPerformed

	private void TracuuKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TracuuKHActionPerformed
		// TODO add your handling code here:
		new Timkiemkhach().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_TracuuKHActionPerformed

	private void QLKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QLKHActionPerformed
		// TODO add your handling code here:
		new QLKH().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_QLKHActionPerformed

	private void TCSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TCSActionPerformed
		// TODO add your handling code here:
		new Timkiemsach().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_TCSActionPerformed

	private void QLNXBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QLNXBActionPerformed
		// TODO add your handling code here:
		new QLNXB().setVisible(true);
		this.setVisible(false);

	}// GEN-LAST:event_QLNXBActionPerformed

	private void ChamCongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ChamCongActionPerformed
		// TODO add your handling code here:
		if (chucvu == 1) {
			JOptionPane.showMessageDialog(this, "Nhân viên không được sử dụng chức năng này.");
			return;
		}
		new Chamcong().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_ChamCongActionPerformed

	private void TCNVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TCNVActionPerformed
		// TODO add your handling code here:
		if (chucvu == 1) {
			JOptionPane.showMessageDialog(this, "Nhân viên không được sử dụng chức năng này.");
			return;
		}
		new Timkiemnhanvien().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_TCNVActionPerformed

	private void QLNVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QLNVActionPerformed
		// TODO add your handling code here:
		if (chucvu == 1) {
			JOptionPane.showMessageDialog(this, "Nhân viên không được sử dụng chức năng này.");
			return;
		}
		new QLNV().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_QLNVActionPerformed

	private void QLSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QLSActionPerformed
		// TODO add your handling code here:
		new QLSach().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_QLSActionPerformed

	private void TCHDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TCHDActionPerformed
		// TODO add your handling code here:
		new Timkiemhd().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_TCHDActionPerformed

	private void QLHDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QLHDActionPerformed
		// TODO add your handling code here:
		new LapHD().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_QLHDActionPerformed

	private void TKHDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TKHDActionPerformed
		// TODO add your handling code here:
		new ThongkeHD().setVisible(true);
		this.setVisible(false);

	}// GEN-LAST:event_TKHDActionPerformed

	private void TCNXBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TCNXBActionPerformed
		// TODO add your handling code here:
		new TimkiemNXB().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_TCNXBActionPerformed

	private void TCTGActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TCTGActionPerformed
		new TimkiemTG().setVisible(true);
		this.setVisible(false);
		// TODO add your handling code here:
	}// GEN-LAST:event_TCTGActionPerformed

	private void QLTGActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QLTGActionPerformed
		// TODO add your handling code here:
		new QLTG().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_QLTGActionPerformed

	private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
		// TODO add your handling code here:
		if (JOptionPane.showConfirmDialog(this, "Bạn có muốn rời khỏi ứng dụng không?", "Cảnh báo",
				JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
			new DangNhap().setVisible(true);
			this.setVisible(false);
		}
	}// GEN-LAST:event_btnThoatActionPerformed

	private void ThemTKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
		// TODO add your handling code here:
		if (chucvu == 1) {
			JOptionPane.showMessageDialog(this, "Nhân viên không được sử dụng chức năng này.");
			return;
		}
		new ThemTK().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_btnThoatActionPerformed

	private void SuaTKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
		// TODO add your handling code here:
		new SuaTK().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_btnThoatActionPerformed

	private void XoaTKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
		// TODO add your handling code here:
		if (chucvu == 1) {
			JOptionPane.showMessageDialog(this, "Nhân viên không được sử dụng chức năng này.");
			return;
		}
		new XoaTK().setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_btnThoatActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new QL("Admin").setVisible(true);

			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem ChamCong;
	private javax.swing.JMenuItem QLHD;
	private javax.swing.JMenuItem QLKH;
	private javax.swing.JMenuItem QLNV;
	private javax.swing.JMenuItem QLNXB;
	private javax.swing.JMenuItem QLS;
	private javax.swing.JMenuItem QLTG;
	private javax.swing.JMenuItem TCHD;
	private javax.swing.JMenuItem TCNV;
	private javax.swing.JMenuItem TCNXB;
	private javax.swing.JMenuItem TCS;
	private javax.swing.JMenuItem TCTG;
	private javax.swing.JMenuItem TKHD;
	private javax.swing.JMenuItem TKS;
	private javax.swing.JMenuItem TracuuKH;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenu jMenu6;
	private javax.swing.JMenu jMenu7;
	private javax.swing.JMenu jMenu8;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel lblThongTinNV;
	private javax.swing.JButton btnDangXuat;
	private javax.swing.JMenuItem XoaTK;
	private javax.swing.JMenuItem ThemTK;
	private javax.swing.JMenuItem SuaTK;

	// End of variables declaration//GEN-END:variables

	private void timkiemkhachActionPerformed(ActionEvent evt) {
		throw new UnsupportedOperationException("Not supported yet."); // To change body of generated methods, choose
																		// Tools | Templates.
	}
}
