/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import org.hibernate.internal.build.AllowSysOut;

import dao.NhaXuatBanDAO;
import dao.SachDAO;
import dao.TacGiaDAO;
import dao.impl.NhaXuatBanImpl;
import dao.impl.SachImpl;
import dao.impl.TacGiaImpl;
import entity.NhaXuatBan;
import entity.Sach;
import entity.TacGia;

/**
 *
 * @author LENOVO
 */
public class QLSach extends JFrame implements ActionListener, MouseListener {

	/**
	 * Creates new form QLSach
	 */
	public QLSach() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGiaThanh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        X = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        cbbTheLoai = new javax.swing.JComboBox<>();
        cbbTacGia = new javax.swing.JComboBox<>();
        cbbNhaXB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý sách");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Tác giả");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Tên sách");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Thể loại");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Giá thành");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tác giả", "NXB", "Giá thành", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnThem.setBackground(new java.awt.Color(255, 102, 0));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setText("Thêm sách");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 102, 0));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setText("Cập nhật Thông Tin ");

        btnXoa.setBackground(new java.awt.Color(255, 102, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setText("Xóa Thông Tin ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Số lượng");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Mã sách");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("NXB");

        X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        X.setForeground(new java.awt.Color(255, 0, 0));
        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 102, 0));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setText("Làm Mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        cbbTheLoai.setModel(
        		new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Sách Chính trị – pháp luật","Sách Khoa học công nghệ", "Sách Kinh tế","Sách Văn học nghệ thuật",

        																	"Sách Văn hóa xã hội – Lịch sử","Sách Giáo trình","Sách Truyện, tiểu thuyết","Sách Tâm lý","Sách tâm linh","Sách tôn giáo","Sách Sách thiếu nhi"

				}));

        cbbTacGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));

        cbbNhaXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(txtTen)
                            .addComponent(txtSoLuong)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaThanh)
                            .addComponent(jLabel6)
                            .addComponent(cbbTheLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbTacGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbNhaXB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(164, 164, 164)
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoa)
                                .addGap(143, 143, 143)
                                .addComponent(btnRefresh)
                                .addGap(104, 104, 104))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(407, 407, 407)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(X))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(X)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbNhaXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtGiaThanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(16, 16, 16)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa)
                        .addComponent(btnRefresh))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnSua)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
		setLocationRelativeTo(null);

//        
		btnSua.addActionListener(this);
		btnXoa.addActionListener(this);
		btnThem.addActionListener(this);
		btnRefresh.addActionListener(this);
		table.addMouseListener(this);

		btnSua.setEnabled(false);
		btnXoa.setEnabled(false);

		txtMa.setEnabled(false);
		txtMa.setText(phatSinhMa());

//      
		modelTable = (DefaultTableModel) table.getModel();

		List<Sach> dsSach = sachDAO.getDsSach();
		addTable_sql(dsSach);

		addJcomboBox();

//        

	}// </editor-fold>//GEN-END:initComponents

	private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
		// TODO add your handling code here:

	}// GEN-LAST:event_btnThemActionPerformed

	private void XActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_XActionPerformed
		// TODO add your handling code here:
		new QL(QL.taiKhoan).setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_XActionPerformed

	private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnXoaActionPerformed

	private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnRefreshActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new QLSach().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTable table;
	private javax.swing.JButton X;
	private javax.swing.JButton btnSua;
	private javax.swing.JButton btnRefresh;
	private javax.swing.JButton btnThem;
	private javax.swing.JButton btnXoa;
	private javax.swing.JComboBox<String> cbbNhaXB;
	private javax.swing.JComboBox<String> cbbTacGia;
	private javax.swing.JComboBox<String> cbbTheLoai;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField txtGiaThanh;
	private javax.swing.JTextField txtMa;
	private javax.swing.JTextField txtSoLuong;
	private javax.swing.JTextField txtTen;
	private DefaultTableModel modelTable;

	SachDAO sachDAO = new SachImpl();

	// End of variables declaration//GEN-END:variables
	@Override
	public void mouseClicked(MouseEvent arg0) {

		int row = table.getSelectedRow();

		txtMa.setText(modelTable.getValueAt(row, 0).toString());
		txtGiaThanh.setText(modelTable.getValueAt(row, 5).toString());
		txtTen.setText(modelTable.getValueAt(row, 1).toString());
		txtSoLuong.setText(modelTable.getValueAt(row, 6).toString());
//
		cbbTheLoai.setSelectedItem(modelTable.getValueAt(row, 2).toString());
		cbbTacGia.setSelectedItem(modelTable.getValueAt(row, 3).toString());
		cbbNhaXB.setSelectedItem(modelTable.getValueAt(row, 4).toString());

//		
		btnSua.setEnabled(true);
		btnXoa.setEnabled(true);
		btnThem.setEnabled(false);

	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void actionPerformed(ActionEvent arg0) {
		Object o = arg0.getSource();
		if (o.equals(btnRefresh)) {
			xoaRongJText();
		} else if (o.equals(btnThem)) {
			if (check_data()) {
				getThemSach();
			}
		} else if (o.equals(btnSua)) {
			if (check_data()) {
				getSuaSach();
			}
		} else if (o.equals(btnXoa)) {
			if (check_data()) {
				getXoaSach();
			}
		}

	}

//
	private void getXoaSach() {
		String maXoa = txtMa.getText().trim();
		int row = table.getSelectedRow();
		String hoten = modelTable.getValueAt(row, 1).toString();
		
		if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin của sách mã số:' " + maXoa+" ' có tên :' "+hoten+" '" + "Không? ", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
			sachDAO.xoaSach(maXoa);
			
			xoaRongJText();
			addTable_sql(sachDAO.getDsSach());
		}
	}

	//
	private void getSuaSach() {
		int row = table.getSelectedRow();
		String ma = txtMa.getText().trim();
		String hoten = modelTable.getValueAt(row, 1).toString();
		if (JOptionPane.showConfirmDialog(this,
				"Bạn có muốn sửa thông tinh sách có mã số:' " + ma + " ' có tên :' " + hoten + " '" + " không?",
				"Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {

			String ten = txtTen.getText().trim();
			double giaThanh = Double.parseDouble(txtGiaThanh.getText().trim());
			System.out.println(txtGiaThanh.getText().trim());
			System.out.println(giaThanh);
			int soLuong = Integer.parseInt(txtSoLuong.getText().trim());
//		
			String theLoai = cbbTheLoai.getSelectedItem().toString();
			String tacGiaString = cbbTacGia.getSelectedItem().toString();
			String nhaXBString = cbbNhaXB.getSelectedItem().toString();

			NhaXuatBan nhaXB = new NhaXuatBan("NXB" + nhaXBString.substring(0, 5));
			TacGia tacGia = new TacGia("TG" + tacGiaString.substring(0, 5));
			Sach a = new Sach(ma, ten, theLoai, giaThanh, soLuong, tacGia, nhaXB);

			if (sachDAO.suaSach(a)) {
				JOptionPane.showMessageDialog(this, "Cập nhật thành công.");

				xoaRongJText();

				addTable_sql(sachDAO.getDsSach());
			}
		}
	}

	//
	private void getThemSach() {
		String ma = txtMa.getText().trim();
		double giaThanh = Double.parseDouble(txtGiaThanh.getText().trim());
		System.out.println(txtGiaThanh.getText().trim());
		System.out.println(giaThanh);
		String ten = txtTen.getText().trim();
		int soLuong = Integer.parseInt(txtSoLuong.getText().trim());
//		
		String theLoai = cbbTheLoai.getSelectedItem().toString();
		String tacGiaString = cbbTacGia.getSelectedItem().toString();
		String nhaXBString = cbbNhaXB.getSelectedItem().toString();

		NhaXuatBan nhaXB = new NhaXuatBan("NXB" + nhaXBString.substring(0, 5));
		TacGia tacGia = new TacGia("TG" + tacGiaString.substring(0, 5));
		Sach a = new Sach(ma, ten, theLoai, giaThanh, soLuong, tacGia, nhaXB);

		if (sachDAO.themSach(a)) {
			JOptionPane.showMessageDialog(this, "Thêm thành công.");

			modelTable.addRow(new Object[] { a.getMaSach(), a.getTenSach(), a.getLoai(), tacGiaString, nhaXBString,
					a.getGiaThanh(), a.getSoLuong() });

			xoaRongJText();

		}

	}

	private void xoaRongJText() {
		txtMa.setText(phatSinhMa());
		txtGiaThanh.setText("");
		txtTen.setText("");
		txtSoLuong.setText("");
//
		cbbNhaXB.setSelectedIndex(0);
		cbbTacGia.setSelectedIndex(0);
		cbbTheLoai.setSelectedIndex(0);

		//
		btnSua.setEnabled(false);
		btnXoa.setEnabled(false);
		btnThem.setEnabled(true);
	}

	private String phatSinhMa() {
		String ma_new = null;
		String ma_old = sachDAO.getMaCuoi();

		String ma0_2 = ma_old.substring(0, 1);
		String ma1_6 = ma_old.substring(1, 6);

		int n = Integer.parseInt(ma1_6) + 1;

		if (n < 10) {
			ma_new = ma0_2 + "0000" + n;
		} else if (n < 100) {
			ma_new = ma0_2 + "000" + n;
		} else if (n < 1000) {
			ma_new = ma0_2 + "00" + n;
		} else if (n < 10000) {
			ma_new = ma0_2 + "0" + n;
		} else if (n < 99999) {
			ma_new = ma0_2 + "" + n;
		} else
		{
			ma_new = "KH99999";
			System.err.println("Full ma");
			JOptionPane.showMessageDialog(this, "Bá»™ nhá»› Ä‘Ã£ bá»‹ Ä‘áº§y");
			
		}

		return ma_new;
	}

//	
	private void addJcomboBox() {
		TacGiaDAO tacGiaDAO = new TacGiaImpl();

		List<TacGia> dsTacGia = tacGiaDAO.getDsTacGia();

		for (TacGia a1 : dsTacGia) {
			String tacGia = a1.getMaTG().substring(2, 7) + "--" + a1.getTenTG();
			cbbTacGia.addItem(tacGia);
		}
//		
		NhaXuatBanDAO nhaXuatBanDAO = new NhaXuatBanImpl();

		List<NhaXuatBan> dsNhaXuatBan = nhaXuatBanDAO.getDsNhaXuatBan();
		for (NhaXuatBan a2 : dsNhaXuatBan) {
			String nhaXB = a2.getMaNXB().substring(3, 8) + "--" + a2.getTenNXB();
			cbbNhaXB.addItem(nhaXB);
		}

	}

//	
	private void addTable_sql(List<Sach> dsSach) {
		DefaultTableModel dm = (DefaultTableModel) table.getModel();
		dm.getDataVector().removeAllElements();

		for (Sach a : dsSach) {
			String tacGia = a.getTacGia().getMaTG().substring(2, 7) + "--" + a.getTacGia().getTenTG();
			String nhaXB = a.getNhaXB().getMaNXB().substring(3, 8) + "--" + a.getNhaXB().getTenNXB();

			modelTable.addRow(new Object[] {
//					"MÃ£ sÃ¡ch", "TÃªn sÃ¡ch", "Thá»ƒ loáº¡i", "TÃ¡c giáº£", "NXB", "GiÃ¡ thÃ nh", "Sá»‘ lÆ°á»£ng"
					a.getMaSach(), a.getTenSach(), a.getLoai(), tacGia, nhaXB, a.getGiaThanh(), a.getSoLuong()

			});
		}
	}

//	
	private boolean check_data() {
		// TODO Auto-generated method stub
		return true;
	}
//	
}
