/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import dao.NhanvienDAO;
import dao.impl.NhanvienImpl;
import entity.KhachHang;
import entity.NhanVien;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kha
 */
public class Timkiemnhanvien extends JFrame implements ActionListener {

	private String tk = QL.taiKhoan;
	private DefaultTableModel modelTable;
	NhanvienDAO nhanVienDao = new NhanvienImpl();

	/**
	 * Creates new form Timkiemnhanvien
	 */
	public Timkiemnhanvien() {
		initComponents();
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
		X.addActionListener(this);

		cbbNam.addActionListener(this);
		cbbThang.addActionListener(this);
		cbbNgay.addActionListener(this);
		btnTimKiem.addActionListener(this);
		btnRefresh.addActionListener(this);

//        
		modelTable = (DefaultTableModel) table.getModel();
		addTable_sql();
//        addComboBox();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		X = new javax.swing.JButton();
		txtHoTenNV = new swing.TextField();
		txtDiaChiNV = new swing.TextField();
		txtSoDTNV = new swing.TextField();
		cbbThang = new swing.Combobox();
		cbbNam = new swing.Combobox();
		jScrollPane1 = new javax.swing.JScrollPane();
		table = new swing.Table();
		jLabel7 = new javax.swing.JLabel();
		txtMa = new swing.TextField();
		btnRefresh = new swing.Button();
		jLabel5 = new javax.swing.JLabel();
		cbbCaLam = new swing.Combobox();
		cbbNgay = new swing.Combobox();
		btnTimKiem = new swing.Button();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(153, 255, 153));
		jPanel1.setPreferredSize(new java.awt.Dimension(1472, 805));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
		jLabel1.setText("Tìm Kiếm Nhân Viên");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 51, 51));
		jLabel4.setText("Năm Sinh");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 51, 51));
		jLabel2.setText("Họ Tên");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 51, 51));
		jLabel6.setText("Địa Chỉ");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 51, 51));
		jLabel3.setText("Số Điện Thoại");

		X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		X.setForeground(new java.awt.Color(255, 0, 0));
		X.setText("X");
		X.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				XActionPerformed(evt);
			}
		});

		txtHoTenNV.setHintText("Hoàng Kha Khoa");

		txtDiaChiNV.setHintText("556 Đinh Tiên Hoàng");

		txtSoDTNV.setHintText("0222222222");

		cbbThang.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

		cbbNam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2021", "2020", "2019", "2018", "2017",
				"2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004",
				"2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991",
				"1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978",
				"1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965",
				"1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952",
				"1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939",
				"1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926",
				"1925", "1924", "1923", "1922", "1921" }));

		table.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã nhân viên", "Tên nhân viên", "Số điện thoại", "Năm sinh", "Ca làm", "Địa chỉ" }));
		table.setShowGrid(true);
		jScrollPane1.setViewportView(table);

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 51, 51));
		jLabel7.setText("Mã nhân viên");

		txtMa.setHintText("NV0001");

		btnRefresh.setText("Làm mới");
		btnRefresh.setColor1(new java.awt.Color(255, 51, 51));
		btnRefresh.setColor2(new java.awt.Color(255, 153, 153));
		btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnRefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRefreshActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 51, 51));
		jLabel5.setText("Ca Làm");

		cbbCaLam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
		cbbCaLam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbbCaLamActionPerformed(evt);
			}
		});

		cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16",
						"17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

		btnTimKiem.setText("Tìm kiếm");
		btnTimKiem.setColor1(new java.awt.Color(255, 51, 51));
		btnTimKiem.setColor2(new java.awt.Color(255, 153, 153));
		btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTimKiemActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(234, 234, 234).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(X))
						.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel7)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 271,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2).addComponent(jLabel6))
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup().addGap(57, 57, 57)
														.addComponent(txtHoTenNV,
																javax.swing.GroupLayout.PREFERRED_SIZE, 271,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
														.createSequentialGroup()
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(btnTimKiem,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 133,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(txtDiaChiNV,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 271,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(150, 150, 150)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel5)
														.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
																99, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(jPanel1Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(cbbNgay,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						61,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(18, 18, 18)
																				.addComponent(cbbThang,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						61,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(cbbNam,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						89,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addComponent(txtSoDTNV,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				271,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addComponent(cbbCaLam,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 61,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(281, 281,
										281)))
								.addContainerGap(329, Short.MAX_VALUE))))
				.addComponent(jScrollPane1));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(X).addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtHoTenNV, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
										.addGap(13, 13, 13)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtDiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6)))
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtSoDTNV, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE,
																36, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(cbbCaLam, javax.swing.GroupLayout.DEFAULT_SIZE, 39,
														Short.MAX_VALUE)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void XActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_XActionPerformed
		// TODO add your handling code here:

		new QL(QL.taiKhoan).setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_XActionPerformed

	private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimKiemActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnTimKiemActionPerformed

	private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnRefreshActionPerformed

	private void cbbCaLamActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbbCaLamActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cbbCaLamActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Timkiemnhanvien.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Timkiemnhanvien.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Timkiemnhanvien.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Timkiemnhanvien.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Timkiemnhanvien().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton X;
	private swing.Button btnRefresh;
	private swing.Button btnTimKiem;
	private swing.Combobox cbbCaLam;
	private swing.Combobox cbbNam;
	private swing.Combobox cbbNgay;
	private swing.Combobox cbbThang;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private swing.Table table;
	private swing.TextField txtDiaChiNV;
	private swing.TextField txtHoTenNV;
	private swing.TextField txtMa;
	private swing.TextField txtSoDTNV;

	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();

		if (o.equals(cbbThang)) {
			getCBBThang();
		} else if (o.equals(cbbNam)) {
			if (cbbNam.getSelectedIndex() == 0) {
				cbbNam.setSelectedIndex(0);
				cbbNgay.setSelectedIndex(0);
				cbbThang.setSelectedIndex(0);
			}
			getCBBNam();
		} else if (o.equals(btnRefresh)) {
			XoaRongJText();
		} else if (o.equals(X)) {
			new QL(tk).setVisible(true);
			this.setVisible(false);
		} else if (o.equals(btnTimKiem)) {

			List<NhanVien> dsNhanVien = new ArrayList<NhanVien>();

			String ma = txtMa.getText().trim();
			String hoten = txtHoTenNV.getText().trim();
			String diaChi = txtDiaChiNV.getText().trim();
			String soDT = txtSoDTNV.getText().trim();
			String macl = cbbCaLam.getSelectedItem().toString().trim();

			int n = 1;

			if (ma.equals("") && hoten.equals("") && diaChi.equals("") && soDT.equals("") && !check_ngay()) {
				n = -1;
				JOptionPane.showMessageDialog(this, "Hãy nhập dữ liệu cần tìm kiếm");

				addTable_sql2(nhanVienDao.getDsNhanVien());
				txtHoTenNV.requestFocus();
			}

			if (ma.length() > 0 && n == 1) {
				NhanVien a = nhanVienDao.timKiem_id(ma);

				if (a == null) {
					JOptionPane.showMessageDialog(this,
							"Mã " + ma + " không có trong danh sách.\nBạn hãy thử tìm kiếm theo nhưng thông tin khác.");
					txtMa.selectAll();
					txtMa.requestFocus();
				} else {
					DefaultTableModel dm = (DefaultTableModel) table.getModel();
					dm.getDataVector().removeAllElements();

					modelTable.addRow(new Object[] { a.getMaNV(), a.getTenNV(), a.getSoDT(), a.getDiaChi() });
				}

				n = -1;
			}
//			if(macl.length() >0 && n==1) {
//				NhanVien a= (NhanVien) nhanVienDao.getDsNhanVien_calam(macl);
//				System.out.println(macl);
//				if (a == null) {
//					JOptionPane.showMessageDialog(this,
//							"Mã " + ma + " không có trong danh sách.\nBạn hãy thử tìm kiếm theo nhưng thông tin khác.");
//					
//				} else {
//					DefaultTableModel dm = (DefaultTableModel) table.getModel();
//					dm.getDataVector().removeAllElements();
//
//					modelTable.addRow(new Object[] { a.getMaNV(), a.getTenNV(), a.getSoDT(), a.getDiaChi() });
//				}
//
//				n = -1;
//			}
//			dsNhanVien = nhanVienDAO.getDsNhanVien();
//			=======================================================
			if (hoten.length() > 0 && n == 1) {
				dsNhanVien = nhanVienDao.getDsNhanVien_Ten(dsNhanVien, hoten);

				if (dsNhanVien.size() != 0) {

					addTable_sql2(dsNhanVien);

				} else {
					JOptionPane.showMessageDialog(this,
							"Không tìm thấy.\nHãy kiểm tra có thể bạn đã nhập sai dữ liệu.\nTrước mỗi từ hãy viết hoa và có dấu");

					txtHoTenNV.selectAll();
					txtHoTenNV.requestFocus();
					n = -1;

					DefaultTableModel dm = (DefaultTableModel) table.getModel();
					dm.getDataVector().removeAllElements();
					addTable_sql();
				}
			}
//			=======================================================
			if (check_ngay() && n == 1) {
				String dd = cbbNgay.getSelectedItem().toString();
				String mm = cbbThang.getSelectedItem().toString();
				String yy = cbbNam.getSelectedItem().toString();

				dsNhanVien = nhanVienDao.getDsNhanVien_NgaySinh(dsNhanVien, dd, mm, yy);

				if (dsNhanVien.size() != 0) {

					addTable_sql2(dsNhanVien);

				} else {
					JOptionPane.showMessageDialog(this,
							"Không tìm thấy.\nHãy kiểm tra có thể bạn đã nhập sai ngày sinh.");

					n = -1;
					DefaultTableModel dm = (DefaultTableModel) table.getModel();
					dm.getDataVector().removeAllElements();
					addTable_sql();
				}

			}

//			=======================================================
			if (soDT.length() > 0 && n == 1) {
				dsNhanVien = nhanVienDao.getDsNhanVien_soDT(dsNhanVien, soDT);

				if (dsNhanVien.size() != 0) {

					addTable_sql2(dsNhanVien);

				} else {
					JOptionPane.showMessageDialog(this,
							"Không tìm thấy.\nHãy kiểm tra có thể bạn đã nhập sai số diện thoại.");

					txtSoDTNV.selectAll();
					txtSoDTNV.requestFocus();
					n = -1;

					DefaultTableModel dm = (DefaultTableModel) table.getModel();
					dm.getDataVector().removeAllElements();
					addTable_sql();
				}
			}
//			=======================================================

//			=======================================================
			if (diaChi.length() > 0 && n == 1) {
				dsNhanVien = nhanVienDao.getDsNhanVien_DiaChi(dsNhanVien, diaChi);

				if (dsNhanVien.size() != 0) {

					addTable_sql2(dsNhanVien);

				} else {
					JOptionPane.showMessageDialog(this,
							"Không tìm thấy.\nHãy kiểm tra có thể bạn đã nhập sai dữ liệu.");
					txtDiaChiNV.selectAll();
					txtDiaChiNV.requestFocus();
					n = -1;

					DefaultTableModel dm = (DefaultTableModel) table.getModel();
					dm.getDataVector().removeAllElements();
					addTable_sql();
				}
			}

		}
	}

	private boolean check_ngay() {
		System.out.println("check_ngay()");
		if (cbbNgay.getSelectedIndex() == 0 && cbbThang.getSelectedIndex() == 0 && cbbNam.getSelectedIndex() == 0) {
			return false;
		}
		return true;
	}

	private void XoaRongJText() {
		txtMa.setText("");
		txtHoTenNV.setText("");
		txtDiaChiNV.setText("");
		txtSoDTNV.setText("");
//
		DefaultTableModel dm = (DefaultTableModel) table.getModel();
		dm.getDataVector().removeAllElements();
//		
		addTable_sql();
//		
		cbbNam.setSelectedIndex(0);
		cbbNgay.setSelectedIndex(0);
		cbbThang.setSelectedIndex(0);
//		addComboBox();
	}

	private boolean check_data() {
		// TODO Auto-generated method stub

		return true;
	}

	private void addTable_sql() {

		List<NhanVien> dsNhanVien = nhanVienDao.getDsNhanVien();

		for (NhanVien a : dsNhanVien) {
//			 "Mã Khách hàng", "Tên Khách hàng", "Ngày sinh", "Số điện thoại",  "Địa chỉ" "Email",
			modelTable.addRow(new Object[] { a.getMaNV(), a.getTenNV(), a.getSoDT(), a.getNamSinh(), a.getCaLam(),
					a.getDiaChi() });
		}
	}

	private void addTable_sql2(List<NhanVien> dsNhanVien) {

		DefaultTableModel dm = (DefaultTableModel) table.getModel();
		dm.getDataVector().removeAllElements();

		for (NhanVien a : dsNhanVien) {
			modelTable.addRow(new Object[] { a.getMaNV(), a.getTenNV(), a.getSoDT(), a.getNamSinh(), a.getCaLam(),
					a.getDiaChi() });
		}
	}

	private void getCBBNam() {
		String dd = cbbNgay.getSelectedItem().toString();
		String mm = cbbThang.getSelectedItem().toString();
		int yy = Integer.parseInt(cbbNam.getSelectedItem().toString());

		if (((yy % 4 == 0) && (yy % 100 != 0)) || (yy % 400 == 0)) {
			if (mm.equals("02")) {
				cbbNgay.setModel(new DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07",
						"08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23",
						"24", "25", "26", "27", "28", "29" }));
			} else if (mm.equals("04") || mm.equals("06") || mm.equals("09") || mm.equals("11")) {
				cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05",
						"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21",
						"22", "23", "24", "25", "26", "27", "28", "29", "30" }));

			} else {
				cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05",
						"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21",
						"22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
			}

		} else {
			if (mm.equals("02")) {
				cbbNgay.setModel(new DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07",
						"08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23",
						"24", "25", "26", "27", "28" }));
			} else if (mm.equals("04") || mm.equals("06") || mm.equals("09") || mm.equals("11")) {
				cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05",
						"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21",
						"22", "23", "24", "25", "26", "27", "28", "29", "30" }));

			} else {
				cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05",
						"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21",
						"22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
			}

		}

		cbbNgay.setSelectedItem(dd);

	}

	private void getCBBThang() {

		String dd = cbbNgay.getSelectedItem().toString();
		String mm = cbbThang.getSelectedItem().toString();
		int yy = Integer.parseInt(cbbNam.getSelectedItem().toString());

		if (mm.equalsIgnoreCase("02")) {
			if (((yy % 4 == 0) && (yy % 100 != 0)) || (yy % 400 == 0)) {
				cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05",
						"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21",
						"22", "23", "24", "25", "26", "27", "28", "29" }));
			} else {
				cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05",
						"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21",
						"22", "23", "24", "25", "26", "27", "28" }));
			}

		} else if (mm.equals("04") || mm.equals("06") || mm.equals("09") || mm.equals("11")) {
			cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05",
					"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21",
					"22", "23", "24", "25", "26", "27", "28", "29", "30" }));

		} else {
			cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05",
					"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21",
					"22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
		}
		cbbNgay.setSelectedItem(dd);

	}

}
